### ISSUE TITLE
Cannot execute command 'dueladmin' in plugin DuelMe v0.19.1 - plugin is disabled.

### ISSUE THREAD

**Issue by mistek131995** [teozfrank/DuelMe#115]
[02:04:58] [Server thread/INFO]: mistek issued server command: /dueladmin create Duel
[02:04:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'dueladmin' in plugin DuelMe v0.19.1 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [Spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by teozfrank** [comment]
need to see the full log please.
