### ISSUE TITLE
doesnt let players join arena

### ISSUE THREAD

**Issue by theshadyonehd** [teozfrank/DuelMe#14]
im using the latest version of the plugin and can create arenas but when players try to use it it says " there are no free arenas...."

**Comment by teozfrank** [comment]
Any console errors? Steps to reproduce the problem?

**Comment by theshadyonehd** [comment]
no errors, 

steps:
1. create a arena
2. setspawns
3. invite someone to play
4. the other player accepts.

**Comment by gpjunior** [comment]
[00:32:15 INFO]: Toshka issued server command: /dueladmin create 1
[00:32:36 INFO]: Toshka issued server command: /dueladmin setspawnpoint1 1
[00:32:44 INFO]: Toshka issued server command: /dueladmin setspawnpoint2 1
[00:33:30 INFO]: Toshka issued server command: /duel list
[00:33:40 INFO]: Toshka issued server command: /dueladmin list
[00:33:53 INFO]: Toshka issued server command: /dueladmin
[00:34:18 INFO]: Toshka issued server command: /duel send Toshka
[00:34:22 INFO]: Toshka issued server command: /duel send Uragan2303
[00:34:51 INFO]: Uragan2303 issued server command: /duel accept Toshka
[00:34:51 WARN]: java.lang.NullPointerException
[00:34:51 WARN]: at com.teozcommunity.teozfrank.duelme.util.DuelManager.updateDuelStatusSign(DuelManager.java:754)
[00:34:51 WARN]: at com.teozcommunity.teozfrank.duelme.util.DuelManager.startDuel(DuelManager.java:416)
[00:34:51 WARN]: at com.teozcommunity.teozfrank.duelme.util.DuelManager.acceptRequest(DuelManager.java:378)
[00:34:51 WARN]: at com.teozcommunity.teozfrank.duelme.commands.duel.AcceptCmd.run(AcceptCmd.java:56)
[00:34:51 WARN]: at com.teozcommunity.teozfrank.duelme.commands.DuelExecutor.onCommand(DuelExecutor.java:107)
[00:34:51 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:34:51 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:34:51 WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[00:34:51 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[00:34:51 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[00:34:51 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[00:34:51 WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by teozfrank** [comment]
What version are you using?

**Comment by teozfrank** [comment]
This has been fixed in the latest public release on spigot and bukkit.
