### ISSUE TITLE
PlayerDeathEvent

### ISSUE THREAD

**Issue by kristiantomov** [teozfrank/DuelMe#36]
[19:24:56 ERROR]: Could not pass event PlayerDeathEvent to DuelMe v0.9.16.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:501) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:486) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeat
hEvent(CraftEventFactory.java:378) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:402)
[craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.j
ava:801) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.jav
a:794) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.j
ava:481) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:995)
 [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:10
48) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:1289) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [
craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [
craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukki
t-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:6
72) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
35) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
28) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:536) [craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bu
kkit/entity/Player$Spigot;
        at com.teozcommunity.teozfrank.duelme.events.PlayerDeath.onPlayerDeath(P
layerDeath.java:80) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:300) ~[craftbukkit-1.8.8.jar:git-Bukkit-880a532]
        ... 22 more
[19:24:56 INFO]: [DuelMe] Tomoff1 was killed in a duel by dani881!

Here is the log, when player dies.

**Comment by teozfrank** [comment]
What version of spigot are you using?

**Comment by teozfrank** [comment]
closed as user is not using the correct plugin dependencies.
