### ISSUE TITLE
Error on disable

### ISSUE THREAD

**Issue by KingFaris10** [teozfrank/DuelMe#52]
`[14:36:38] [Server thread/INFO]: [DuelMe] Enabling DuelMe v0.10.0
[14:36:38] [Server thread/INFO]: [DuelMe] [Info] Enabling.
[14:36:38] [Server thread/INFO]: [DuelMe] [Info] WorldEdit found!
[14:36:38] [Server thread/INFO]: [DuelMe] [Info] Successfully loaded 1 Duel Arena(s).
[14:36:38] [Server thread/INFO]: [DuelMe] [Warning] Your config.yml is out of date! please remove or back it up before using the plugin!
[14:36:38] [Server thread/INFO]: [DuelMe] [Warning] There were 1 startup error(s), plugin DISABLED!
[14:36:38] [Server thread/INFO]: [DuelMe] Disabling DuelMe v0.10.0
[14:36:38] [Server thread/INFO]: [DuelMe] [Info] Disabling.
[14:36:38] [Server thread/ERROR]: Error occurred while disabling DuelMe v0.10.0 (Is it up to date?)
java.lang.NullPointerException
	at com.teozcommunity.teozfrank.duelme.util.FileManager.saveDuelArenas(FileManager.java:232) ~[?:?]
	at com.teozcommunity.teozfrank.duelme.main.DuelMe.onDisable(DuelMe.java:133) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at com.teozcommunity.teozfrank.duelme.main.DuelMe.checkErrors(DuelMe.java:158) [DuelMe.jar:?]
	at com.teozcommunity.teozfrank.duelme.main.DuelMe.onEnable(DuelMe.java:103) [DuelMe.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-7ebe8ff-5eceede]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by teozfrank** [comment]
[DuelMe] [Warning] Your config.yml is out of date! please remove or back it up before using the plugin!

Update your config.yml to the latest version.

**Comment by KingFaris10** [comment]
Oh, I didn't pick that up, thanks. It'll probably work then.
