### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by TechnoGeek123-321** [teozfrank/DuelMe#87]
Hi, I recently updated my server and this plugin to 1.11.2. I get this error in the console on startup:
`[08:11:36 WARN]: [DuelMe] Task #158 for DuelMe v0.17.5 generated an exception
java.lang.LinkageError: loader constraint violation: when resolving method "com.github.teozfrank.duelme.util.UpdateChecker.<init>(Lcom/github/teozfrank/duelme/main/DuelMe;I)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/github/teozfrank/duelme/threads/UpdateCheckerThread, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/github/teozfrank/duelme/util/UpdateChecker, have different Class objects for the type com/github/teozfrank/duelme/main/DuelMe used in the signature
        at com.github.teozfrank.duelme.threads.UpdateCheckerThread.run(UpdateCheckerThread.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`
Thanks!

**Comment by teozfrank** [comment]
Will take a look at this now.

**Comment by teozfrank** [comment]
Does this still occur with the latest version?

**Comment by teozfrank** [comment]
Closing as no response made, please create a new issue if this still persists, thanks.
